#!/bin/sh

set -e

OUTPUT_FILE=
WORDLIST_FILE=
opener='pub const words = [_][]const u8{'
closer='};'

usage() {
	printf 'usage: %s [-o <output_zig_file>] <wordlist_file>\n' "${0##*/}"
}

error() {
	printf 'error: %s\n' "$1" >&2
	exit 1
}

while getopts 'o:' opt; do
	case "$opt" in
	o) OUTPUT_FILE="$OPTARG" ;;
	*)
		usage
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

if [ -z "$1" ]; then
	usage
	error 'provide a file to parse as the first argument'
fi

if [ ! -f "$1" ]; then
	error "file \"$1\" does not exist"
fi

WORDLIST_FILE="$1"

if [ -n "$OUTPUT_FILE" ]; then
	exec >&"$OUTPUT_FILE"
fi

printf '%s\n' "$opener"

while IFS= read -r word; do
	printf '    "%s",\n' "$word"
done <"$WORDLIST_FILE"

printf '%s\n' "$closer"
